services:
  ist:
    build:
      context: ./ist
      dockerfile: Dockerfile-deploy
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - CACHE_HOST=cache
      - CACHE_PASS=${CACHE_PASS}
    depends_on:
      - db
      - cache

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  cache:
    build:
      context: ./cache
    restart: always
    environment:
      - REDIS_PASSWORD=${CACHE_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - cache
    ports:
      - 80:8000
    volumes:
      - static-data:/vol/static


volumes:
  postgres-data:
  static-data:
