name: astrowebsite

services:
  db:
    restart: always
    image: postgres:17rc1-bookworm
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
     - "5432:5432"
    volumes:
     - ./postgres/scripts:/docker-entrypoint-initdb.d

  # this is some user interface to the docker database.
  adminer:
    restart: always
    image: adminer
    container_name: adminer
    ports:
     - "8080:8080"
  